apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1lxe
  namespace: eedri-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/eedri-tenant/eyal-test-app/devfile-sample-1lxe@sha256:4c81eb5ff1cd1473d41f4f9601ab877a19e75c09cf715280d65afa947c22b58a
        name: my-nodejs
        resources: {}
status: {}
