apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-qxr0
  namespace: eedri-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/eedri-tenant/eyal-test-app/devfile-sample-python-basic-qxr0@sha256:f1d566831721b855ba2ec0d9fa25d6a29019d5d741f14191ed417ec0098af97d
        name: my-python
        resources: {}
status: {}
