apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-7ogk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/eedri-tenant/eyal-test-app/devfile-sample-go-basic-7ogk@sha256:df6ca7446bdc36e01d82a7f4d30278edac68c195c4070fc7b2d8e375375b6ac3
        name: my-go
        resources: {}
status: {}
