apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-7ogk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/eedri-tenant/eyal-test-app/devfile-sample-go-basic-7ogk@sha256:6aa5550ec40658ddd2c7e1fa385097fb6f9d3e2a796ec788493a588723833cd9
        name: my-go
        resources: {}
status: {}
